import railway from "../assets/exam/Railways_All.png";
import image from "../assets/exam/image.png";
import SSC_All from "../assets/exam/SSC_All_.png";
import Homeguard from "../assets/exam/UP_Homeguard.png";

export default { railway, image, SSC_All, Homeguard };
export const MockTestCardData = [
  {
    name: "SSC CHSL Mock Test Series 2025",
    logo: SSC_All,
    tire: "Tier I & Tier II",
    totalTest: 250,
    language: "Hindi & English",
  },
  {
    name: "SSC GD Constable 2026 Mock Test Series",
    logo: SSC_All,
    tire: "Complete Syllabus",
    totalTest: 300,
    language: "Hindi & English",
  },
  {
    name: "SSC CPO Mock Test Series 2025",
    logo: SSC_All,
    tire: "Tier I & Tier II (DP SI)",
    totalTest: 180,
    language: "Hindi & English",
  },
  {
    name: "Bihar JEEVIKA Mock Test 2025",
    logo: image,
    tire: "Latest Exam Pattern",
    totalTest: 120,
    language: "Hindi",
  },
  {
    name: "SSC MTS & Havaldar Mock Test Series 2025",
    logo: SSC_All,
    tire: "Paper I & II",
    totalTest: 210,
    language: "Hindi & English",
  },
  {
    name: "RRB NTPC Under Graduate 2025",
    logo: railway,
    tire: "CBT 1 + CBT 2",
    totalTest: 260,
    language: "Hindi & English",
  },
  {
    name: "RRB NTPC Mock Test Series 2024-25",
    logo: railway,
    tire: "CBT 1 + CBT 2",
    totalTest: 300,
    language: "Hindi & English",
  },
  {
    name: "UP Home Guard Mock Test Series 2025",
    logo: Homeguard,
    tire: "Latest Exam Pattern",
    totalTest: 150,
    language: "Hindi",
  },
  {
    name: "SSC JE Civil Mock Test Series 2025",
    logo: SSC_All,
    tire: "Paper I & II",
    totalTest: 180,
    language: "Hindi & English",
  },
  {
    name: "SSC Stenographer Grade C & D Mock Test Series 2025",
    logo: SSC_All,
    tire: "Computer Based Test",
    totalTest: 130,
    language: "Hindi & English",
  },
  {
    name: "RRB Group D Mock Test Series 2025",
    logo: railway,
    tire: "CBT Exam",
    totalTest: 200,
    language: "Hindi & English",
  },
  {
    name: "RRB ALP & Technician Mock Test Series 2025",
    logo: railway,
    tire: "CBT 1 + CBT 2",
    totalTest: 240,
    language: "Hindi & English",
  },
  {
    name: "Bihar Police Constable Mock Test Series 2025",
    logo: image,
    tire: "Latest Exam Pattern",
    totalTest: 190,
    language: "Hindi",
  },
  {
    name: "UP Police Constable Mock Test Series 2025",
    logo: Homeguard,
    tire: "Complete Syllabus",
    totalTest: 210,
    language: "Hindi",
  },
  {
    name: "SSC JHT (Hindi Translator) Mock Test Series 2025",
    logo: SSC_All,
    tire: "Paper 1 & 2",
    totalTest: 160,
    language: "Hindi & English",
  },
  {
    name: "Delhi Police Constable Mock Test Series 2025",
    logo: image,
    tire: "CBT Exam",
    totalTest: 170,
    language: "Hindi & English",
  },
  {
    name: "CTET January 2025 Paper I Mock Test Series",
    logo: image,
    tire: "Paper 1",
    totalTest: 150,
    language: "Hindi & English",
  },
  {
    name: "CTET January 2025 Paper II Mock Test Series",
    logo: image,
    tire: "Paper 2",
    totalTest: 160,
    language: "Hindi & English",
  },
  {
    name: "SSC CGL Mock Test Series 2025",
    logo: SSC_All,
    tire: "Tier I, II, III",
    totalTest: 320,
    language: "Hindi & English",
  },
  {
    name: "SSC Scientific Assistant IMD Test Series 2025",
    logo: SSC_All,
    tire: "CBT Exam",
    totalTest: 180,
    language: "Hindi & English",
  },
  {
    name: "DRDO Technician A Mock Test Series 2025",
    logo: image,
    tire: "Tier I & Tier II",
    totalTest: 210,
    language: "Hindi & English",
  },
  {
    name: "Navy SSR & AA Mock Test Series 2025",
    logo: image,
    tire: "CBT Exam",
    totalTest: 140,
    language: "Hindi & English",
  },
  {
    name: "Airforce Agniveer Vayu Mock Test Series 2025",
    logo: image,
    tire: "Phase I & II",
    totalTest: 190,
    language: "Hindi & English",
  },
  {
    name: "Bihar SI & Sergeant Mock Test Series 2025",
    logo: image,
    tire: "Pre + Mains",
    totalTest: 220,
    language: "Hindi",
  },
  {
    name: "UPSSSC PET Mock Test Series 2025",
    logo: Homeguard,
    tire: "Complete Syllabus",
    totalTest: 260,
    language: "Hindi",
  },
  {
    name: "UPSSSC VDO 2025 Mock Test Series",
    logo: Homeguard,
    tire: "Prelim + Mains",
    totalTest: 150,
    language: "Hindi",
  },
  {
    name: "CTET July 2025 Paper 1 Mock Test Series",
    logo: image,
    tire: "Paper 1",
    totalTest: 150,
    language: "Hindi & English",
  },
  {
    name: "CTET July 2025 Paper 2 Mock Test Series",
    logo: image,
    tire: "Paper 2",
    totalTest: 160,
    language: "Hindi & English",
  },
  {
    name: "RRB JE Mock Test Series 2025",
    logo: railway,
    tire: "CBT 1 + CBT 2",
    totalTest: 280,
    language: "Hindi & English",
  },
  {
    name: "RRB Group C (Paramedical) Mock Test Series 2025",
    logo: railway,
    tire: "CBT Exam",
    totalTest: 160,
    language: "Hindi & English",
  },
  {
    name: "SSC Selection Post Phase 13 Test Series 2025",
    logo: SSC_All,
    tire: "Matric + Inter + Graduate",
    totalTest: 240,
    language: "Hindi & English",
  },
  {
    name: "NDA & NA Exam 2025 Mock Test Series",
    logo: image,
    tire: "Paper I & II",
    totalTest: 200,
    language: "Hindi & English",
  },
  {
    name: "Indian Coast Guard Navik GD Mock Test Series 2025",
    logo: image,
    tire: "Stage I & II",
    totalTest: 150,
    language: "Hindi & English",
  },
  {
    name: "SSC Stenographer Grade C & D Mock Test Series 2025",
    logo: SSC_All,
    tire: "CBT Exam",
    totalTest: 180,
    language: "Hindi & English",
  },
  {
    name: "SSC JHT Mock Test Series 2025",
    logo: SSC_All,
    tire: "Paper I & II",
    totalTest: 150,
    language: "Hindi & English",
  },
  {
    name: "SSC Delhi Police Constable Mock Test Series 2025",
    logo: SSC_All,
    tire: "CBT Exam",
    totalTest: 230,
    language: "Hindi & English",
  },
  {
    name: "SSC Selection Post Phase 14 Mock Test Series 2025",
    logo: SSC_All,
    tire: "Matric | Intermediate | Graduate",
    totalTest: 210,
    language: "Hindi & English",
  },
  {
    name: "UP Police Constable Mock Test Series 2025",
    logo: Homeguard,
    tire: "CBT Exam",
    totalTest: 260,
    language: "Hindi",
  },
  {
    name: "UP Police SI Mock Test Series 2025",
    logo: Homeguard,
    tire: "Pre + Mains",
    totalTest: 190,
    language: "Hindi",
  },
  {
    name: "MP Police Constable Mock Test Series 2025",
    logo: image,
    tire: "CBT Exam",
    totalTest: 210,
    language: "Hindi",
  },
  {
    name: "Rajasthan Police Constable Mock Test Series 2025",
    logo: image,
    tire: "CBT Exam",
    totalTest: 200,
    language: "Hindi",
  },
  {
    name: "Rajasthan LDC Mock Test Series 2025",
    logo: image,
    tire: "CBT Exam",
    totalTest: 160,
    language: "Hindi",
  },
  {
    name: "Bihar Police Constable Mock Test Series 2025",
    logo: image,
    tire: "CBT Exam",
    totalTest: 230,
    language: "Hindi",
  },
  {
    name: "Bihar Police SI Mock Test Series 2025",
    logo: image,
    tire: "Pre + Mains",
    totalTest: 180,
    language: "Hindi",
  },
  {
    name: "CTET January 2026 Mock Test Series (Paper 1)",
    logo: image,
    tire: "Paper I",
    totalTest: 150,
    language: "Hindi & English",
  },
  {
    name: "CTET January 2026 Mock Test Series (Paper 2)",
    logo: image,
    tire: "Paper II",
    totalTest: 160,
    language: "Hindi & English",
  },
  {
    name: "REET Level 1 Mock Test Series 2025",
    logo: image,
    tire: "Level 1",
    totalTest: 140,
    language: "Hindi",
  },
  {
    name: "REET Level 2 Mock Test Series 2025",
    logo: image,
    tire: "Level 2",
    totalTest: 150,
    language: "Hindi",
  },
  {
    name: "AFCAT 1 2025 Mock Test Series",
    logo: image,
    tire: "AFCAT + EKT",
    totalTest: 200,
    language: "Hindi & English",
  },
  {
    name: "CDS 1 2025 Mock Test Series",
    logo: image,
    tire: "Paper I & II",
    totalTest: 210,
    language: "Hindi & English",
  },
  {
    name: "NDA 2 2025 Mock Test Series",
    logo: image,
    tire: "Maths + GAT",
    totalTest: 240,
    language: "Hindi & English",
  },
  {
    name: "RRB Group D Mock Test Series 2025",
    logo: railway,
    tire: "CBT Exam",
    totalTest: 280,
    language: "Hindi & English",
  },
  {
    name: "RRB ALP Technician Mock Test Series 2025",
    logo: railway,
    tire: "CBT 1 + CBT 2 + CBAT",
    totalTest: 260,
    language: "Hindi & English",
  },
];
